### ISSUE TITLE
Unresolved reference: MiniCalcLexer

### ISSUE THREAD

**Issue by exaV** [ftomassetti/antlr-kotlin#4]
I get the following compile error when using the kotlin target: Unresolved reference: MiniCalcLexer

Perhaps because there are some remnant of MiniCalcLexder in Kotlin.stg?

See for example: https://github.com/ftomassetti/antlr-kotlin/blob/58a8cbeffb8ebdf8e1 34fbaad0d215a4342f9c56/antlr-kotlin-target/src/main/resources/org/antlr/v4/tool/templates/codegen/Kotlin/Kotlin.stg#L245

**Comment by ftomassetti** [comment]
Wow, yes that stuff should be removed. The problem is that I tried the code exactly with a grammar named like that so I did not get the errors :D

**Comment by ftomassetti** [comment]
Submitting PR #6 to fix this
