### ISSUE TITLE
Compile errors in generated code

### ISSUE THREAD

**Issue by exaV** [ftomassetti/antlr-kotlin#5]
Using this grammar https://gist.github.com/exaV/fcbb1fcfd0478a57ffd5f4402207291a

**Comment by ftomassetti** [comment]
What errors exactly?

**Comment by exaV** [comment]
I think it's best if you copy the grammar into antlr-kotlin-examples-jvm and see for yourself.

I think most of there errors were due to missing {} brackets in a fraction of the when statements. Other when statements had something like this:
```
when(somevar){
EQUAL -> LIKE -> {
//somecode
 }
}
```
which I think is a remnant of javas switch fallthrough. In Kotlin it would be `EQUAL, LIKE -> {}`

There are some minor other erros as well. Here is the output of build for the grammar above:

> 
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (345, 4): Expecting '->'
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (345, 5): Expecting an expression
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (345, 6): Expecting an expression, is-condition or in-condition
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (351, 4): Expecting '->'
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (351, 5): Expecting an expression
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (351, 6): Expecting an expression, is-condition or in-condition
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (356, 5): Expecting '->'
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (440, 19): Expecting an expression, is-condition or in-condition
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (496, 19): Expecting an expression, is-condition or in-condition
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (557, 4): Expecting '->'
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (557, 5): Expecting an expression
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (557, 6): Expecting an expression, is-condition or in-condition
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (562, 5): Expecting '->'
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (701, 4): Expecting '->'
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (701, 5): Expecting an expression
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (701, 6): Expecting an expression, is-condition or in-condition
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (709, 4): Expecting '->'
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (709, 5): Expecting an expression
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (709, 6): Expecting an expression, is-condition or in-condition
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (716, 5): Expecting '->'
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (762, 4): Expecting '->'
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (762, 5): Expecting an expression
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (762, 6): Expecting an expression, is-condition or in-condition
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (769, 5): Expecting '->'
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (791, 14): Expecting comma or ')'
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (341, 4): 'if' must have both main and 'else' branches if used as an expression
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (341, 4): Incompatible types: Unit and Int
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (347, 4): 'if' must have both main and 'else' branches if used as an expression
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (347, 4): Incompatible types: Unit and Int
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (353, 4): 'if' must have both main and 'else' branches if used as an expression
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (353, 4): Incompatible types: Unit and Int
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (553, 4): 'if' must have both main and 'else' branches if used as an expression
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (553, 4): Incompatible types: Unit and Int
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (559, 4): 'if' must have both main and 'else' branches if used as an expression
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (559, 4): Incompatible types: Unit and Int
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (695, 4): 'if' must have both main and 'else' branches if used as an expression
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (695, 4): Incompatible types: Unit and Int
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (703, 4): 'if' must have both main and 'else' branches if used as an expression
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (703, 4): Incompatible types: Unit and Int
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (711, 4): 'if' must have both main and 'else' branches if used as an expression
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (711, 4): Incompatible types: Unit and Int
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (756, 4): 'if' must have both main and 'else' branches if used as an expression
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (756, 4): Incompatible types: Unit and Int
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (764, 4): 'if' must have both main and 'else' branches if used as an expression
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (764, 4): Incompatible types: Unit and Int
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (790, 36): Type mismatch: inferred type is TerminalNode but List<TerminalNode> was expected
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (791, 11): A type annotation is required on a value parameter
e: /Users/rick/Documents/GitHub/antlr-kotlin/antlr-kotlin-examples-jvm/generated-src/antlr/cqlParser.kt: (791, 15): A type annotation is required on a value parameter
:compileKotlin FAILED

**Comment by ftomassetti** [comment]
Fixed by #12
